### ISSUE TITLE
MAGIC_MASK check incorrect in rpi-eeprom-config

### ISSUE THREAD

**Issue by Googulator** [raspberrypi/rpi-eeprom#11]
In [rpi-eeprom-config, line 40](https://github.com/raspberrypi/rpi-eeprom/blob/391573d9000640db1b022942a56b68e9bfdb7e6c/rpi-eeprom-config#L40), the magic mask check is done incorrectly; a value of 0xFFFFFFFF will check out as valid.

**Comment by timg236** [comment]
Resolved in PR12
