### ISSUE TITLE
Add support for booting from a "superfloppy" disk

### ISSUE THREAD

**Issue by worproject** [raspberrypi/rpi-eeprom#120]
The boot ROM itself can boot just fine from a superfloppy disk (i've tested this with the recovery.bin image), but if there's no recovery image on the disk, it loads the EEPROM bootloader which can only boot from MBR-partitioned disks.

This worked fine on the Pi 3 as the bootcode was loaded by the boot ROM directly from the SD card.

**Comment by timg236** [comment]
Right now, I can't

**Comment by worproject** [comment]
Indeed, GPT support would be better. In fact I was using superfloppy to workaround the lack of native GPT support.

**Comment by timg236** [comment]
Thanks that’s useful to know

**Comment by timg236** [comment]
Since we are adding GPT and 0xef partition support we may as well add SuperFloppy whilst we are editing that bit of code.
Hopefully, fairly standard MBR (primary + extended) and GPT will then just work.

**Comment by timg236** [comment]
This should be fixed by e87bc4da8d983aa6e7c3edcf8cd823b76e50e65e

The binaries are available in this release which can be flashed using the Raspberry Pi Imager
https://github.com/raspberrypi/rpi-eeprom/releases/tag/v2020.05.26-137ad

**Comment by timg236** [comment]
Fix is now available via rpi-eeprom apt package
