### ISSUE TITLE
Pi not powering down

### ISSUE THREAD

**Issue by 5t4n5** [raspberrypi/rpi-eeprom#13]
After updating with the rpi-eeprom my Pi is no longer powering down properly.

Once the screen goes blank and it appears the Pi is powered down, the SSD remains still powered on, both blue light and red light, and the Ethernet light is flashing continuously.

**Comment by timg236** [comment]
That's the expected behaviour in 2019-07-15  because of disabling 3.3V but not 5V (which can't be turned off) is incompatible with some HATs
See release notes
https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/release-notes.md
