### ISSUE TITLE
Download pieeprom.bin from eeprom? (or update just bootloader config)

### ISSUE THREAD

**Issue by Harvie** [raspberrypi/rpi-eeprom#150]
Is it possible to get `pieeprom.bin` back from eeprom? I know i can get bootloader config from eeprom using `vcgencmd bootloader_config`, but is there possibility to get full `pieeprom.bin` backup directly from device?

My use case is following. I am writing simple script for editing bootloader config. It goes something like this:

```bash
#!/bin/sh
# rpi-eeprom-config-edit.sh

vcgencmd bootloader_config | sed -e 's/ *$//;/^$/d' | sort -u > /boot/bootconfig.cur.txt
cp -f /boot/bootconfig.cur.txt /boot/bootconfig.txt
editor /boot/bootconfig.txt
diff /boot/bootconfig.cur.txt /boot/bootconfig.txt
read -p 'Apply changes? ENTER to continue, CTRL+C to abort' null
echo done
```

It downloads current config, opens it in editor, then shows the diff and ask for agreement before flashing it  to eeprom.

Problem is that i don't know how to update config without flashing whole eeprom image again. That means i need to figure out at least one of the following methods:

  1. Figure out how to modify just the configuration without overwriting whole eeprom
  2. Get whole eeprom dump from eeprom, modify that and flash back
  3. Get path to the latest `pieeprom.bin` and use that. (possibility of unwanted upgrade)

There are several bootloader version in `/lib/firmware/raspberrypi/bootloader/` and i don't know  how to safely determine which one to use in my script.

Perhaps i can use something like
```ls -1 /lib/firmware/raspberrypi/bootloader/stable/pieeprom-*.bin | tail -n 1```
to determine latest stable pieeprom version and use that to craft image with modified config... While checking if the eeprom version and image version is different and warning user in such case.

I would like to provide easy and relatively SAFE solution for user to modify bootloader configuration and i would love to hear your opinions, possibly making this into PR later, when i get it to production quality.

**Comment by timg236** [comment]
N.B. For interactive updates please look at this change in raspi-config for inspiration ( it's temporarily reverted until MSD boot is in production release)

In typical UNIX fashion it reuses the rpi-eeprom-update and raspi-config scripts which are pure command line programs with as few dependencies as possible so that they can be re-used on other OSes. 

https://github.com/RPi-Distro/raspi-config/commit/04ec68ab5c8b115f716adf2459f7904aaf7f4486

**Comment by Harvie** [comment]
@timg236 does this mean there are plans to have interactive bootloader config using raspi-config in the future? Including POWER_OFF_ON_HALT option and similar? If that's the case, there's no point for me to write such script myself...

**Comment by timg236** [comment]
raspi-config will offer a simple choice of sd/network boot or sd/usb boot. 

There no plans to include other features right now but there is nothing to stop other people from creating tools and distributing via Github.
