### ISSUE TITLE
Wrong link on https://www.raspberrypi.org/downloads/ ?

### ISSUE THREAD

**Issue by lurch** [raspberrypi/rpi-eeprom#152]
On https://www.raspberrypi.org/downloads/ there's a bit which says "View the full bootloader release notes" which then links to https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md which doesn't seem right. Is it supposed to be linking to https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/release-notes.md ?

**Comment by timg236** [comment]
You need to raise this with the Web Team

**Comment by lurch** [comment]
I don't have access to the Web Team. ping @JamesH65 :wink:

**Comment by JamesH65** [comment]
Done.

**Comment by timg236** [comment]
Thanks @JamesH65 @Jonic  that all looks good
