### ISSUE TITLE
MSD boot device whitelist

### ISSUE THREAD

**Issue by hex007** [raspberrypi/rpi-eeprom#155]
Just like the current blacklist for USB boot with vid/pid combo, it would be great to have a whitelist.

Most of the time I know which msd I am interested in booting from. If I have multiple devices that are being plugged unplugged it is harder to maintain a blacklist. 

An alternative could also be support to define a port where the bootable drive is connected. eg. Bus 01 port 02. This allows me to have multiple drives with same brands connected but not intended for msd boot.

**Comment by timg236** [comment]
The VID exclude list is only so that troublesome USB devices can be completely ignored. We've ruled out storing allow/deny or topology specific lists in the configuration.
As with Pi3 the bootloader will boot from the first bootable device that contains a valid start.elf.
