### ISSUE TITLE
Wake on LAN - Raspberry 4

### ISSUE THREAD

**Issue by vencakratky** [raspberrypi/rpi-eeprom#160]
**Describe the bug**
I'm looking for a possibility enable Wake on LAN on Raspberry Pi4 

**Expected behaviour**
I use Libreelec with Rpi4 - only passive cooling (due to TV noise)
When playing a movie, cpu has about 80-82°C 
in Stand by mode always about 60°C - with Kodi stand by mode
Sometimes i have to shutdown system, because during playback raspberry is restarted (high temperature)
That's why I'm looking for a solution to turn on RPi with WOL from Power Off (Via Home Assistant or Kodi app - Ios)

**SD card boot (please complete the following information):**
 - SD card type
Sandisk 16GB Extreme A1 UHS-I

**Additional context**
I tried the new Raspberry Pi OS and upgrade 
`sudo apt update`
 `sudo apt full-upgrade`
 `sudo rpi-eeprom-update -a`
But high Temperature with passive Cooling still persists
I do not know such problems with temperature and passive cooler on Rpi3 :(

**Comment by timg236** [comment]
Feature requests should be posted to the forums. 

Marking as wontfix because the hardware can't support this
