### ISSUE TITLE
SSD USB Boot - continuous "USB Reset" kernel messages

### ISSUE THREAD

**Issue by cherberg** [raspberrypi/rpi-eeprom#177]
I am a Noob using my RPI 4 to run an iobroker installation for smart home 
I have to say I am a total Linux rookie :-)

I recently moved to boot from USB to increase stability&availability by avoiding degrading SD Cards.

I am was using the latest beta from 15.06.2020 and had irregular crashes (system unreachable) which could only be solved by a hard reset. 

cat /var/log/messages shows alot of entries like this, identical messages are the last ones before such a crash.

`Jul  7 15:30:21 raspberrypi kernel: [   43.521474] usb 2-2: reset SuperSpeed Gen 1 USB device number 2 using xhci_hcd
Jul  7 15:30:54 raspberrypi kernel: [   77.321465] usb 2-2: reset SuperSpeed Gen 1 USB device number 2 using xhci_hcd
Jul  7 15:31:08 raspberrypi kernel: [   90.771615] usb 2-2: reset SuperSpeed Gen 1 USB device number 2 using xhci_hcd
Jul  7 15:51:02 raspberrypi kernel: [ 1284.879522] usb 2-2: reset SuperSpeed Gen 1 USB device number 2 using xhci_hcd
Jul  7 15:51:02 raspberrypi kernel: [ 1284.923015] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00
Jul  7 15:51:02 raspberrypi kernel: [ 1284.923034] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x28 28 00 00 77 13 00 00 01 00 00
Jul  7 15:51:04 raspberrypi kernel: [ 1286.519227] usb 2-2: reset SuperSpeed Gen 1 USB device number 2 using xhci_hcd
Jul  7 15:51:06 raspberrypi kernel: [ 1289.379375] usb 2-2: reset SuperSpeed Gen 1 USB device number 2 using xhci_hcd
Jul  7 15:51:07 raspberrypi kernel: [ 1289.412691] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00
Jul  7 15:51:07 raspberrypi kernel: [ 1289.412701] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x28 28 00 00 7c 42 00 00 01 00 00
Jul  7 15:51:08 raspberrypi kernel: [ 1290.989243] usb 2-2: reset SuperSpeed Gen 1 USB device number 2 using xhci_hcd
`

I also see alot of these:

`Jul  7 12:05:17 raspberrypi kernel: [1011070.851145] JBD2: Detected IO errors while flushing file data on sda2-8
Jul  7 12:05:35 raspberrypi kernel: [1011088.970168] JBD2: Detected IO errors while flushing file data on sda2-8
Jul  7 12:05:46 raspberrypi kernel: [1011100.338956] JBD2: Detected IO errors while flushing file data on sda2-8
Jul  7 12:06:10 raspberrypi kernel: [1011124.471158] JBD2: Detected IO errors while flushing file data on sda2-8
Jul  7 12:10:49 raspberrypi kernel: [1011403.703668] JBD2: Detected IO errors while flushing file data on sda2-8
Jul  7 12:15:05 raspberrypi kernel: [1011659.707904] JBD2: Detected IO errors while flushing file data on sda2-8
`

I just upgraded to the new version from 06.07.2020 a few hours ago but the errors remain.

Maybe this is an error that needs to be fixed. 

If not any help to fix this manually thru configuration would be highly appreciated.

**Comment by timg236** [comment]
Please post support requests on the forums

This Linux USB stack is independent of the bootloader and there are lots of threads about USB as SCSI
https://www.raspberrypi.org/forums/viewtopic.php?t=274595

https://www.raspberrypi.org/forums/viewtopic.php?t=245931
