### ISSUE TITLE
DOn't know how to install the latest eeprom

### ISSUE THREAD

**Issue by Drake008** [raspberrypi/rpi-eeprom#190]
Can someone help me here out?
How do I install the newest USB Boot eeprom to my rapsi 4?
I have a manual for installing an older eeprom.

The commandline there is 

sudo rpi-eeprom-update -d -f /lib/firmware/raspberrypi/bootloader/beta/pieepron-2020-05-15.bin

**Comment by timg236** [comment]
Read the raspberry pi forums or use google but I suggest you don’t change bootloaders unless you have a clear understanding as to the benefits and risks

**Comment by lurch** [comment]
The [README](https://github.com/raspberrypi/rpi-eeprom/blob/master/README.md) in this repo has a helpful link to the [documentation](https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md).
