### ISSUE TITLE
Wrong date in tag

### ISSUE THREAD

**Issue by lurch** [raspberrypi/rpi-eeprom#200]
I guess https://github.com/raspberrypi/rpi-eeprom/releases/tag/v2020.08.31-138a1 was supposed to be `v2020.07.31-138a1` ?

**Comment by lurch** [comment]
Ooops, just noticed that https://github.com/raspberrypi/rpi-eeprom/releases/tag/v2020.07.31-138a1 does exist. Is it possible to delete the wrong tag?

**Comment by timg236** [comment]
garbage collected tags
