### ISSUE TITLE
Black screen while PXE booting

### ISSUE THREAD

**Issue by maluueu** [raspberrypi/rpi-eeprom#240]
**Describe the bug**
After successful boot from PXE the Pi4B only displays a black screen
Trying to boot the same image via SD-Card works as expected.
SSHing into the Pi works both for SD and PXE boot mode.

**To Reproduce**
Boot Raspbian Lite over PXE using this guide: [click here !](https://www.virtuallyghetto.com/2020/07/two-methods-to-network-boot-raspberry-pi-4.html).

**Expected behaviour**
Boot the image over PXE with Desktop GUI.

**Bootloader version and configuration**
bootloader_config:
```
[all]
BOOT_UART=0
WAKE_ON_GPIO=1
POWER_OFF_ON_HALT=0
DHCP_TIMEOUT=45000
DHCP_REQ_TIMEOUT=4000
TFTP_FILE_TIMEOUT=30000
ENABLE_SELF_UPDATE=1
DISABLE_HDMI=0
BOOT_ORDER=0x412
```
bootloader_version:
```
Sep  3 2020 13:11:43
version c305221a6d7e532693cc7ff57fddfc8649def167 (release)
timestamp 1599135103
```

**Comment by timg236** [comment]
Please check the instructions in the guide again or use the Raspberry Pi forums for support questions.
