### ISSUE TITLE
Feature: TFTP Blocksize Option

### ISSUE THREAD

**Issue by Muxxxi** [raspberrypi/rpi-eeprom#25]
It would be a really great thing if the TFTP Blocksize Option (RFC 2348) could be specified in the bootconf.txt to use bigger values than the 512 bytes default. That would be helpful, to speed up the network boot of systems with "big" ramdisks.

**Comment by timg236** [comment]
RFC2348 with to increase the block-size to 1024 is on the the "nice to have" todo list for first TFTP release. That would half the number of requests/responses. Unfortunately, larger block sizes is probably too disruptive a change.

**Comment by timg236** [comment]
Implemented in the latest beta release.
