### ISSUE TITLE
No Bootable Partitions

### ISSUE THREAD

**Issue by STUKguy** [raspberrypi/rpi-eeprom#253]
Hi, 

So I thought I would make a back up of my SD card with Win32, once done I plugged my SD card back into my PI4 and this happened 
![20201111_125003](https://user-images.githubusercontent.com/66088795/98813659-75dc7b00-241c-11eb-9686-b7a72243cc3a.jpg)
I didn't hit delete/overright on Win32 so unsure why this has happened I'm burning the image I did to an SD card to see what happens. 
But just incase does this mean I need to redo my Raspbian image?

**Comment by timg236** [comment]
Please see the Raspberry Pi General discussion forums for support questions
https://www.raspberrypi.org/forums/viewforum.php?f=63

That looks like a blank ex-FAT SD card so presumably, the disk copying process went wrong

**Comment by STUKguy** [comment]
@timg236 ah sorry did realize I posted to the wrong form. Thank you for your help
