### ISSUE TITLE
Authorization with regards to packaging for other distributions

### ISSUE THREAD

**Issue by FrostbyteGR** [raspberrypi/rpi-eeprom#257]
Hello,

I would like to ask if (besides the terms already mentioned in the [LICENSE file](https://github.com/raspberrypi/rpi-eeprom/blob/master/LICENSE)) there's any sort of specific authorization required, to package and maintain the rpi-eeprom package, under different distributions (i.e. CentOS) that have chosen to provide ports for the Raspberry Pi 4 as well. And if so, can we have the necessary authorization from you, to do so?

Thank you!

**Comment by ghollingworth** [comment]
No, there is nothing more you require

**Comment by FrostbyteGR** [comment]
> 
> 
> No, there is nothing more you require

I appreciate the swift and timely response, thank you very much!
