### ISSUE TITLE
"latest" firmware repo

### ISSUE THREAD

**Issue by lurch** [raspberrypi/rpi-eeprom#26]
Should `raspberry_pi4_network_boot_beta.md` be recommending https://github.com/raspberrypi/firmware as the source of latest firmware, rather than https://github.com/Hexxeh/rpi-update ?
ping @popcornmix

**Comment by popcornmix** [comment]
Well, rpi-update the tool you use to get latest firmware from  https://github.com/raspberrypi/firmware (technically it comes from https://github.com/Hexxeh/rpi-firmware but the two repos have the same firmware contents).

At some point it should refer to using apt to get latest firmware, but at this stage rpi-update firmware is required for testing this. There is a fair amount of dependency between the bootcode in eeprom and the start.elf firmware so I suspect needing firmware as new as latest eeprom update will continue to be required for quite a while.

**Comment by lurch** [comment]
To clarify, I wasn't querying whether "rpi-update firmware" was required for network booting (which is of course entirely understandable, given the "beta" status of it all), I was just querying whether https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/raspberry_pi4_network_boot_beta.md should be linking to https://github.com/raspberrypi/firmware (since IMHO that looks much more like an "official" URL than https://github.com/Hexxeh/rpi-firmware , even if the two repos have the same contents).

Although I now see that https://github.com/raspberrypi/firmware gets updated more frequently than https://github.com/Hexxeh/rpi-firmware so perhaps the distinction is deliberate? (in which case feel free to close this issue!)

**Comment by timg236** [comment]
Network boot is no longer beta and that document doesn't exist. Closing
