### ISSUE TITLE
If you are able to run Linux and run vcgencmd then the bootloader and EEPROM must be running correctly.

### ISSUE THREAD

**Issue by m88beau** [raspberrypi/rpi-eeprom#265]
If you are able to run Linux and run vcgencmd then the bootloader and EEPROM must be running correctly. 

--Thats the problem, I cannot run vcgencmd....

_Originally posted by @timg236 in https://github.com/raspberrypi/rpi-eeprom/issues/263#issuecomment-742822746_

**Comment by timg236** [comment]
Linux is running so this is not a bootloader bug. The firmware is failing for some unrelated reason.
