### ISSUE TITLE
Rpi is disconnected from the network after 24H

### ISSUE THREAD

**Issue by leranp** [raspberrypi/rpi-eeprom#340]
**Mandatory information**
* Raspberry Pi model : Pi 4 - 4GB
* Board revision (cat /proc/cpuinfo | grep Revision): c03111
* Operating system version . Raspbian OS
* Details of any hardware attached e.g. links to USB : SSD via USB
* Photo of the HDMI diagnostics screen, UART trace.

**Describe the bug**
I have a problem that happened before I updated to 2021-03-18-vl805-000138a1 version,
but now after the update to 2021-04-29-vl805-000138a1 the problem back again,
the rpi is exit from the network (LAN) but rpi is still on and function.
only reboot fix it , in the past I tried to replace the RJ45 cable and the charger (to original ) .
this is a 3 months old rpi 4 , the problem happened in exactly 24hour after the booting.
before the rpi 4 I had a rpi3b+ and I didn't had any issue like this

**Bootloader version and configuration**
2021-04-29-vl805-000138a1

this is the log files
daemon.log
```
May 24 20:20:38 HomeAssistant rngd[364]: stats: bits received from HRNG source: 780064
May 24 20:20:38 HomeAssistant rngd[364]: stats: bits sent to kernel pool: 723072
May 24 20:20:38 HomeAssistant rngd[364]: stats: entropy added to kernel pool: 723072
May 24 20:20:38 HomeAssistant rngd[364]: stats: FIPS 140-2 successes: 39
May 24 20:20:38 HomeAssistant rngd[364]: stats: FIPS 140-2 failures: 0
May 24 20:20:38 HomeAssistant rngd[364]: stats: FIPS 140-2(2001-10-10) Monobit: 0
May 24 20:20:38 HomeAssistant rngd[364]: stats: FIPS 140-2(2001-10-10) Poker: 0
May 24 20:20:38 HomeAssistant rngd[364]: stats: FIPS 140-2(2001-10-10) Runs: 0
May 24 20:20:38 HomeAssistant rngd[364]: stats: FIPS 140-2(2001-10-10) Long run: 0
May 24 20:20:38 HomeAssistant rngd[364]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
May 24 20:20:38 HomeAssistant rngd[364]: stats: HRNG source speed: (min=403.472; avg=514.884; max=528.457)Kibits/s
May 24 20:20:38 HomeAssistant rngd[364]: stats: FIPS tests speed: (min=11.966; avg=16.925; max=31.371)Mibits/s
May 24 20:20:38 HomeAssistant rngd[364]: stats: Lowest ready-buffers level: 2
May 24 20:20:38 HomeAssistant rngd[364]: stats: Entropy starvations: 0
May 24 20:20:38 HomeAssistant rngd[364]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
```

**Comment by lurch** [comment]
If the Pi has been running for 24 hours, then this is probably an issue for https://github.com/raspberrypi/linux rather than https://github.com/raspberrypi/rpi-eeprom ?
