### ISSUE TITLE
"RPI-CM4Lite-R1-3"+"2021-07-6" boot loader cause power LED is always on even system already shutdown!

### ISSUE THREAD

**Issue by ciarahsu** [raspberrypi/rpi-eeprom#381]
"RPI-CM4Lite-R1-3"+"2021-07-6" boot loader cause power LED is always on even system already shutdown. 
Does anyone have the same issue and how to solve it ? 
Does anyone know which bootloader verison can solve this issue ? 

thanks for your kindly answer!

**Comment by timg236** [comment]
None of them. The red led is supposed to on whenever the power is connected

**Comment by ciarahsu** [comment]
thanks for your reply! but 
"RPI-CM4Lite-R1-3"+"2020-10-2"  boot loader, power LED will be"oiff" after system shutdown even power adapter is still connected. why "2020-10-2"  and  "+"2021-07-6"" have difference result ?
