### ISSUE TITLE
The script fails to detect rpi4 running in 64bit mode.

### ISSUE THREAD

**Issue by asavah** [raspberrypi/rpi-eeprom#4]
https://github.com/raspberrypi/rpi-eeprom/blob/master/rpi-eeprom-update#L355

This check should be changed to make use of /proc/device-tree which should be more reliable.
`cat /proc/cpuinfo` on 4.19.x ARM64 kernel built from from raspberrypi/linux repo
```
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3
```

**Comment by MilhouseVH** [comment]
```
grep Revision /proc/cpuinfo | awk '{print $3}'
od -tx1 /proc/device-tree/system/linux,revision | head -1 | tr -d ' ' | cut -b9-
```
works in LibreELEC and Raspbian, returning:
RPi4 (4GB):
```
c03111
0c03111
```
and
RPi3+:
```
2a020d3
2a020d3
```

**Comment by asavah** [comment]
in 64 bit mode:
`grep Revision /proc/cpuinfo | awk '{print $3}'`
returns nothing

`od -tx1 /proc/device-tree/system/linux,revision | head -1 | tr -d ' ' | cut -b9-`
returns
```
0c03111
```

**Comment by timg236** [comment]
I might change this to get the board id from 'vcgencmd otp_dump' because the output format is defined by the firmware.

**Comment by asavah** [comment]
Fixed by https://github.com/raspberrypi/rpi-eeprom/commit/47f985542de707b624af5e293c571b7c86163706

Thanks
