### ISSUE TITLE
rpi-eeprom_13.7-1 - using zst compression, dpkg can't install

### ISSUE THREAD

**Issue by bwauto** [raspberrypi/rpi-eeprom#443]
### Describe the bug

When updating system packages on a fresh Bullseye image (2022-09-22 image), retrieved and written to card with RPi Imager, running apt update/upgrade, pulls in rpi-eeprom_13.7-1, which seems to contain control/data tars compressed with zst, not xz. Since debian dpkg can't handle zst yet, install fails.

### Steps to reproduce the behaviour

sudo apt update && sudo apt upgrade - assuming you'll get rpi-eeprom_13.7-1 as an upgradeable package, this should fail when dpkg gets to it.

### Device (s)

Other

### Bootloader configuration.

Stock RPi 2b Rev 1.1 with 7" official touchscreen, desktop OS, otherwise vanilla.

### System

Raspberry Pi reference 2022-09-22
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 8a42abcd1dbd8c9c1fdfca4e0c3778255b2f9cc4, stage5

$ vcgencmd version
Aug 26 2022 14:04:36
Copyright (c) 2012 Broadcom
version 102f1e848393c2112206fadffaaf86db04e98326 (clean) (release) (start)

$ uname -a
Linux psychopi 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux

**Comment by XECDesign** [comment]
https://github.com/RPi-Distro/repo/issues/311
