### ISSUE TITLE
Pi4 update EEPROM stop

### ISSUE THREAD

**Issue by mywp** [raspberrypi/rpi-eeprom#470]
### Describe the bug

Pi4 update eeprom stop at "SIG vl805.sig 548581c70a71d4da17a8d0eb314db518a1d3592249e893e42c020c0a8f53a75f 0"
print at UART
nothing others:
SIG vl805.sig 548581c70a71d4da17a8d0eb314db518a1d3592249e893e42c020c0a8f53a75f 0

### Steps to reproduce the behaviour

can not run homeassistant
update eeprom

### Device (s)

Raspberry Pi 4 Mod. B

### Bootloader configuration.

rpi-boot-eeprom-recovery-2023-01-11-vl805-000138c0-sd.zip

### Bootloader logs

SIG vl805.sig 548581c70a71d4da17a8d0eb314db518a1d3592249e893e42c020c0a8f53a75f 0

**Comment by timg236** [comment]
Closing because the bug report contains no specific information and this version of the bootloader clearly works for other people. I suggest asking on homeassistant or raspberry pi forums.
