### ISSUE TITLE
pieeprom.original.bin: Expected size error

### ISSUE THREAD

**Issue by CHHE-ledtec** [raspberrypi/rpi-eeprom#473]
### Describe the bug

trying to update bootloader and firmware on cm4 with emmc.

but i am stuck when trying to use the latest stable or any other versions

chhe@pop-os:~/usbboot/recovery$ wget -O pieeprom.original.bin https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/stable/pieeprom-2023-01-11.bin
--2023-04-12 15:33:36--  https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/stable/pieeprom-2023-01-11.bin
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘pieeprom.original.bin’

pieeprom.original.bin                                                           [ <=>                                                                                                                                                                                      ] 134.72K  --.-KB/s    in 0.08s   

2023-04-12 15:33:36 (1.63 MB/s) - ‘pieeprom.original.bin’ saved [137950]

chhe@pop-os:~/usbboot/recovery$ sudo ./update-pieeprom.sh
+ /home/chhe/usbboot/tools/rpi-eeprom-config --config boot.conf --out pieeprom.bin pieeprom.original.bin
ERROR: pieeprom.original.bin: Expected size 524288 bytes actual size 137950 bytes
+ die Failed to update EEPROM image
+ echo Failed to update EEPROM image
Failed to update EEPROM image
+ exit
+ cleanup
+ [ -f  ]
chhe@pop-os:~/usbboot/recovery$ rm -f pieeprom.original.bin
chhe@pop-os:~/usbboot/recovery$ wget -O pieeprom.original.bin https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/stable/pieeprom-2022-12-07.bin
--2023-04-12 15:35:08--  https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/stable/pieeprom-2022-12-07.bin
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘pieeprom.original.bin’

pieeprom.original.bin                                                           [ <=>                                                                                                                                                                                      ] 134.71K  --.-KB/s    in 0.08s   

2023-04-12 15:35:09 (1.64 MB/s) - ‘pieeprom.original.bin’ saved [137944]

chhe@pop-os:~/usbboot/recovery$ sudo ./update-pieeprom.sh
+ /home/chhe/usbboot/tools/rpi-eeprom-config --config boot.conf --out pieeprom.bin pieeprom.original.bin
ERROR: pieeprom.original.bin: Expected size 524288 bytes actual size 137944 bytes
+ die Failed to update EEPROM image
+ echo Failed to update EEPROM image
Failed to update EEPROM image
+ exit
+ cleanup
+ [ -f  ]
chhe@pop-os:~/usbboot/recovery$ ^C
chhe@pop-os:~/usbboot/recovery$ rm -f pieeprom.original.bin
chhe@pop-os:~/usbboot/recovery$ wget -O pieeprom.original.bin https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/stable/pieeprom-2022-10-18.bin
--2023-04-12 15:36:15--  https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/stable/pieeprom-2022-10-18.bin
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘pieeprom.original.bin’

pieeprom.original.bin                                                           [ <=>                                                                                                                                                                                      ] 134.72K  --.-KB/s    in 0.08s   

2023-04-12 15:36:16 (1.63 MB/s) - ‘pieeprom.original.bin’ saved [137950]

chhe@pop-os:~/usbboot/recovery$ sudo ./update-pieeprom.sh
+ /home/chhe/usbboot/tools/rpi-eeprom-config --config boot.conf --out pieeprom.bin pieeprom.original.bin
ERROR: pieeprom.original.bin: Expected size 524288 bytes actual size 137950 bytes
+ die Failed to update EEPROM image
+ echo Failed to update EEPROM image
Failed to update EEPROM image
+ exit
+ cleanup
+ [ -f  ]
chhe@pop-os:~/usbboot/recovery$ rm -f pieeprom.original.bin
chhe@pop-os:~/usbboot/recovery$ wget -O pieeprom.original.bin https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/critical/pieeprom-2023-01-11.bin
--2023-04-12 15:37:46--  https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/critical/pieeprom-2023-01-11.bin
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘pieeprom.original.bin’

pieeprom.original.bin                                                           [ <=>                                                                                                                                                                                      ] 134.76K  --.-KB/s    in 0.08s   

2023-04-12 15:37:47 (1.65 MB/s) - ‘pieeprom.original.bin’ saved [137998]

chhe@pop-os:~/usbboot/recovery$ sudo ./update-pieeprom.sh
+ /home/chhe/usbboot/tools/rpi-eeprom-config --config boot.conf --out pieeprom.bin pieeprom.original.bin
ERROR: pieeprom.original.bin: Expected size 524288 bytes actual size 137998 bytes
+ die Failed to update EEPROM image
+ echo Failed to update EEPROM image
Failed to update EEPROM image
+ exit
+ cleanup
+ [ -f  ]
chhe@pop-os:~/usbboot/recovery$ 
 

### Steps to reproduce the behaviour

cd ~/

git clone --depth=1 https://github.com/raspberrypi/usbboot

cd usbboot

make

cd recovery

rm -f pieeprom.original.bin

curl -L -o pieeprom.original.bin https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/stable/pieeprom-2023-01-11.bin

./update-pieeprom.sh

### Device (s)

Raspberry Pi CM4

### Bootloader configuration.

[all]
BOOT_UART=0
WAKE_ON_GPIO=1
POWER_OFF_ON_HALT=0

# Boot Order Codes, from https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#BOOT_ORDER
# Try SD first (1), followed by, USB PCIe, NVMe PCIe, USB SoC XHCI then network
BOOT_ORDER=0xf25641

# Set to 0 to prevent bootloader updates from USB/Network boot
# For remote units EEPROM hardware write protection should be used.
ENABLE_SELF_UPDATE=1

**Comment by timg236** [comment]
Oh you downloaded the HTML of github with that command.
" wget -O pieeprom.original.bin https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/stable/pieeprom-2023-01-11.bin"
Use git clone instead

**Comment by pelwell** [comment]
The equivalent wget command would be:
```
wget -O pieeprom.original.bin https://github.com/raspberrypi/rpi-eeprom/raw/master/firmware/stable/pieeprom-2023-01-11.bin
```
(notice the `raw` where you had `blob`)
