### ISSUE TITLE
How should the 2712 EEPROM firmware be packaged?

### ISSUE THREAD

**Issue by classabbyamp** [raspberrypi/rpi-eeprom#496]
I am working on updating the packaging of rpi-eeprom for Void Linux.

Does the 2712 firmware also go in /lib/firmware/raspberrypi/bootloader mixed with the 2711 firmware?

**Comment by timg236** [comment]
I recommend you install RPi OS and look there.
It is now /lib/firmware/raspberrypi/bootloader-2711 and /lib/firmware/raspberrypi/bootloader-2712

**Comment by classabbyamp** [comment]
I was looking at the contents of the RPi OS packages but I didn't see it there. thanks

**Comment by timg236** [comment]
> I was looking at the contents of the RPi OS packages but I didn't see it there. thanks

If you are familiar with building .debs (I'm not :)) then the package meta data is here
https://github.com/raspberrypi/rpi-eeprom/tree/debian/bookworm/debian
