### ISSUE TITLE
Tryboot A_B mode still reads tryboot.txt instead of config.txt

### ISSUE THREAD

**Issue by mdsketch** [raspberrypi/rpi-eeprom#504]
### Describe the bug

First time filling a firmware bug, but I am pretty sure its a bug and not just a bad config on my part, let me know if you want any other information

I have tested this on 2 separate Pi4's running this version of the bootloader.
![image](https://github.com/raspberrypi/rpi-eeprom/assets/59035262/733b7d78-5f0b-47d3-8fbd-799bdf54fba6)

I am running on yocto mickeldore with a 6 partition setup: (I was going to test on rpiOS but that was gonna be alot of work)
1 -> autoboot.txt
2 -> bootA
3 -> bootB
5 -> rootfsA
6 -> rootfsB
7 -> data Part

Here is my autoboot.txt
![image](https://github.com/raspberrypi/rpi-eeprom/assets/59035262/eb4140d8-2c40-41d7-a10b-2e78455e4fd7)

I have a mostly stock config.txt with the following modifications: (just placed at the end overriding any defaults
![image](https://github.com/raspberrypi/rpi-eeprom/assets/59035262/698cb1db-da22-4a18-aacc-4356814cfc08)

During a regular boot, we can see the can interface being brough up
![image](https://github.com/raspberrypi/rpi-eeprom/assets/59035262/fc165dae-f5bc-4463-aa8a-dcc3f56014c6)

As well the interface shows up in `ip a` and bluetooth is blocked 

![image](https://github.com/raspberrypi/rpi-eeprom/assets/59035262/aa46fae5-71c6-46b2-b93c-68fca346f356)

However after rebooting with `reboot '0 tryboot'` which the partition is selected correctly (and with uart debugging i can see the bootloader selection process), none of my custom configuration is applied:
![image](https://github.com/raspberrypi/rpi-eeprom/assets/59035262/4bfceceb-b64e-44f4-8da9-5e1613658eea)

![image](https://github.com/raspberrypi/rpi-eeprom/assets/59035262/c8081fbc-6f79-4464-af76-b0b8adb595b4)

My thought was to copy config.txt to tryboot.txt, and sure enough when i do that and reboot with `reboot '0 tryboot'` everything works as expected.

### Steps to reproduce the behaviour

1. Use tryboot mode with autoboot.txt (see my config above)
2. Set custom config.txt options
3. Reboot with `reboot '0 tryboot'` and you should see your config.txt options are not applied
4. Copy config.txt to tryboot.txt
5. Reboot again with `reboot '0 tryboot'` and you should now see your config.txt options are applied

### Device (s)

Raspberry Pi 4 Mod. B

### Bootloader configuration.

![image](https://github.com/raspberrypi/rpi-eeprom/assets/59035262/a288fdd3-296a-48ab-838b-5d7414bd4adc)

**Comment by mdsketch** [comment]
Ok let me get on that

**Comment by mdsketch** [comment]
Ok that's interesting, how do I update that?

I assumed if I update the eeprom, that would be enough

**Comment by timg236** [comment]
In RPi OS apt-update / apt upgrade. Yocto ... no idea but other distros should probably get the firmware binaries from this branch which is used for the APT releases
https://github.com/raspberrypi/rpi-firmware/tree/stable

**Comment by mdsketch** [comment]
Ok yeah, I was just looking at that, I think I see the issue in yocto, of where the oldfirmware is being pulled. Ill take a look over there.

Thanks for the quick responses
