### ISSUE TITLE
Is rpi-eeprom github the support for Pineberry Pi ?

### ISSUE THREAD

**Issue by ffries** [raspberrypi/rpi-eeprom#513]
### Describe the bug

Dear all,

Pineberry.com points to your github to ask questions about NVMe booting:
https://docs.pineberrypi.com/tutorial-booting-from-nvme

`We’ve seen constant firmware changes on the Pi 5 that affect the NVMe boot functionality. This guide will be updated if the configuration changes. Please report NVMe boot related issues to the [official EEPROM repository.](https://github.com/raspberrypi/rpi-eeprom)`

Is this github the right place to ask questions about NVMe booting on the Pineberry top NVMe hat?

Kind regards,
FF

### Steps to reproduce the behaviour

xxx

### Device (s)

Other

### Bootloader configuration.

xxxx

### System

xxx

### Bootloader logs

xxxxx

### USB boot

xxxx

### NVMe boot

xxx

### Network (TFTP boot)

xxx

**Comment by timg236** [comment]
Pineberry and other HAT manufacturers are the initial point of contact for support / interop questions.
I believe the early NVMe HAT hardware was release before the spec was published and doesn’t generate the right signals for autodetect and power management. The workaround is to add PCIE_PROBE=1 to the EEPROM config.
