### ISSUE TITLE
pi5 thermal throttling raises clock

### ISSUE THREAD

**Issue by cleverca22** [raspberrypi/rpi-eeprom#518]
### Describe the bug

if you switch cpufreq to manual mode:
```
echo userspace > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
echo > /sys/devices/system/cpu/cpufreq/policy0/scaling_setspeed 2000000
```
the system will then be locked to 2ghz

if you then cause thermal throttling with for example `stress-ng --cpu 4` and a lack of heatsink
the system will RAISE! the clock
```
root@raspberrypi:~# vcgencmd measure_clock arm ; vcgencmd measure_temp
frequency(0)=2000005120
temp=76.8'C
root@raspberrypi:~# vcgencmd measure_clock arm ; vcgencmd measure_temp
frequency(0)=2000006656
temp=77.4'C
root@raspberrypi:~# vcgencmd measure_clock arm ; vcgencmd measure_temp
frequency(0)=2256007936
temp=82.9'C
```

i suspect the problem, is that the soft-throttling uses a percentage of the max clock, rather then a percentage of what cpufreq requested

further heating, will cause it to throttle more, until it hits 1.5ghz, and temps are under control
but as it backs off, it will over-shoot what cpufreq requested, and bounce around, never settling on the requested clock, until it fully leaves the soft-throttling zone

### Device (s)

Raspberry Pi 5

### Bootloader configuration.

```
root@raspberrypi:~# vcgencmd bootloader_config
[all]
BOOT_UART=1
POWER_OFF_ON_HALT=0
BOOT_ORDER=0xf41
```

### System

```
root@raspberrypi:~# vcgencmd bootloader_version
2024/01/05 15:57:40
version 30cc5f37d65b279e820adb1d9840ad3c1cc98229 (release)
timestamp 1704470260
update-time 1704905906
capabilities 0x0000007f
```

**Comment by timg236** [comment]
Reproduced. The soft-limit scaling was based arm_freq config.txt rather than the current max freq.

**Comment by timg236** [comment]
Closing as fixed
