### ISSUE TITLE
There is no Bootloader Version Option in raspi-config

### ISSUE THREAD

**Issue by microfx** [raspberrypi/rpi-eeprom#534]
sudo raspi-config
Choose Advanced Options
Choose Bootloader Version

It allows you to change the bootloader version between default and latest.

_Originally posted by @peterharperuk in https://github.com/raspberrypi/rpi-eeprom/issues/532#issuecomment-1924162819_
            

There is no option for the bootloader sadly. 

<img width="540" alt="Bildschirmfoto 2024-02-02 um 17 15 19" src="https://github.com/raspberrypi/rpi-eeprom/assets/37987212/7f3edc91-07d8-4416-9d40-100a8a35b19a">

**Comment by lurch** [comment]
That's a super-old version of `raspi-config`. It should look something more like this: https://www.raspberrypi.com/documentation/computers/configuration.html#advanced-options
