### ISSUE TITLE
`rpi-eeprom-update` silently ignores `RPI_EEPROM_USE_FLASHROM` when `flashrom` is not found

### ISSUE THREAD

**Issue by mocknen** [raspberrypi/rpi-eeprom#536]
### Describe the bug

As in the title, `rpi-eeprom-update` silently ignores `RPI_EEPROM_USE_FLASHROM` if `flashrom` is not found.
It would be kind to at least display some warning when the user intentionally sets `RPI_EEPROM_USE_FLASHROM=1`.
I will submit a pull request.

### Steps to reproduce the behaviour

1. Set `RPI_EEPROM_USE_FLASHROM=1` in `/etc/default/rpi-eeprom-update`.
2. Run `rpi-eeprom-update` without installing `flashrom`.

### Device (s)

Raspberry Pi 5

### Bootloader configuration.

.

**Comment by timg236** [comment]
Yes, that's the intended behaviour
