### ISSUE TITLE
Raspberry pi 5 in standby fan is running at full speed, usb is also on

### ISSUE THREAD

**Issue by Zuluuk** [raspberrypi/rpi-eeprom#540]
### Describe the bug

The system is booting normally with no issue.

When the system is halt / shutdown and the power light is red. The fan is running at full speed. USB devices attached is still getting power because lights on the joystick is still on.

### Steps to reproduce the behaviour

I only have the official case and fan, this is not an active cooler. The usb controller i use is a dragon rise with LED switches.

1. Using raspberry os 64 bit, start up and go into gui << the fan at this time should just stop because there is no loads.
2. Shut down / halt the system. The red light power should come on.
3. At this time the fan for some reason goes full speed, the LED on the joystick is still on.

### Device (s)

Raspberry Pi 5

### Bootloader configuration.

[all]
BOOT_UART=1
POWER_OFF_ON_HALT=0
BOOT_ORDER=0xf14

BOOTLOADER: up to date
   CURRENT: Mon  5 Feb 14:38:34 UTC 2024 (1707143914)
    LATEST: Fri  5 Jan 15:57:40 UTC 2024 (1704470260)
   RELEASE: default (/lib/firmware/raspberrypi/bootloader-2712/default)
            Use raspi-config to change the release.

lam@raspberrypi:~ $ rpi-eeprom-config pieeprom.upd
ERROR: Failed to read 'pieeprom.upd'
[Errno 2] No such file or directory: 'pieeprom.upd'

### System

lam@raspberrypi:~ $ cat /etc/rpi-issue
Raspberry Pi reference 2023-12-05
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 70cd6f2a1e34d07f5cba7047aea5b92457372e05, stage4

lam@raspberrypi:~ $ vcgencmd bootloader_version
2024/02/05 14:38:34
version 0e79493d7768139f1868e8cdcf664962d56c62a8 (release)
timestamp 1707143914
update-time 1707409155
capabilities 0x0000007f

lam@raspberrypi:~ $ vcgencmd version
2024/02/05 14:38:34
Copyright (c) 2012 Broadcom
version 0e79493d (release) (embedded)

lam@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.0-rpi8-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux

### Bootloader logs

I dont have GPIO header for this log

### USB boot

lam@raspberrypi:~ $ lsusb -vvv

Bus 004 Device 002: ID 0781:5581 SanDisk Corp. Ultra
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               3.00
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         9
  idVendor           0x0781 SanDisk Corp.
  idProduct          0x5581 Ultra
  bcdDevice            1.00
  iManufacturer           1 SanDisk
  iProduct                2 SanDisk Ultra
  iSerial                 3 A2004461B2035E94
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x002c
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              504mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         8 Mass Storage
      bInterfaceSubClass      6 SCSI
      bInterfaceProtocol     80 Bulk-Only
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst               3
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst               3

Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               3.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0
  bDeviceProtocol         3
  bMaxPacketSize0         9
  idVendor           0x1d6b Linux Foundation
  idProduct          0x0003 3.0 root hub
  bcdDevice            6.01
  iManufacturer           3 Linux 6.1.0-rpi8-rpi-2712 xhci-hcd
  iProduct                2 xHCI Host Controller
  iSerial                 1 xhci-hcd.1
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x001f
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0
      bInterfaceProtocol      0 Full speed (or root) hub
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0004  1x 4 bytes
        bInterval              12
        bMaxBurst               0

Bus 003 Device 002: ID 046d:c063 Logitech, Inc. DELL Laser Mouse
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         8
  idVendor           0x046d Logitech, Inc.
  idProduct          0xc063 DELL Laser Mouse
  bcdDevice           57.00
  iManufacturer           1 DELL
  iProduct                2 DELL USB Laser Mouse
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0022
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower               98mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      71
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0006  1x 6 bytes
        bInterval              10

Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0
  bDeviceProtocol         1 Single TT
  bMaxPacketSize0        64
  idVendor           0x1d6b Linux Foundation
  idProduct          0x0002 2.0 root hub
  bcdDevice            6.01
  iManufacturer           3 Linux 6.1.0-rpi8-rpi-2712 xhci-hcd
  iProduct                2 xHCI Host Controller
  iSerial                 1 xhci-hcd.1
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0019
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0
      bInterfaceProtocol      0 Full speed (or root) hub
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0004  1x 4 bytes
        bInterval              12

Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               3.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0
  bDeviceProtocol         3
  bMaxPacketSize0         9
  idVendor           0x1d6b Linux Foundation
  idProduct          0x0003 3.0 root hub
  bcdDevice            6.01
  iManufacturer           3 Linux 6.1.0-rpi8-rpi-2712 xhci-hcd
  iProduct                2 xHCI Host Controller
  iSerial                 1 xhci-hcd.0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x001f
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0
      bInterfaceProtocol      0 Full speed (or root) hub
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0004  1x 4 bytes
        bInterval              12
        bMaxBurst               0

Bus 001 Device 002: ID 2516:0011 Cooler Master Co., Ltd. Storm Quick Fire TK 6keys
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         8
  idVendor           0x2516 Cooler Master Co., Ltd.
  idProduct          0x0011 Storm Quick Fire TK 6keys
  bcdDevice            1.11
  iManufacturer           1 CM Storm
  iProduct                2 Quickfire TKL 6keys
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x003b
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode           33 US
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      65
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode           33 US
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     115
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1

Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0
  bDeviceProtocol         1 Single TT
  bMaxPacketSize0        64
  idVendor           0x1d6b Linux Foundation
  idProduct          0x0002 2.0 root hub
  bcdDevice            6.01
  iManufacturer           3 Linux 6.1.0-rpi8-rpi-2712 xhci-hcd
  iProduct                2 xHCI Host Controller
  iSerial                 1 xhci-hcd.0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0019
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0
      bInterfaceProtocol      0 Full speed (or root) hub
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0004  1x 4 bytes
        bInterval              12

### NVMe boot

Not used

### Network (TFTP boot)

Not used

**Comment by Zuluuk** [comment]
Video demonstration: https://www.veed.io/view/6dd96d53-2d58-459a-bec2-7068367b8c44?panel=showcase

**Comment by timg236** [comment]
Try setting POWER_OFF_ON_HALT=1 in the EEPROM config to see if that helps

**Comment by Zuluuk** [comment]
> Try setting POWER_OFF_ON_HALT=1 in the EEPROM config to see if that helps

I tried this and it made no difference. I thought the same at the time, I was reading Jeff's guide and thought that it could be a power management issue.

**Comment by timg236** [comment]
Sounds like an issue with the USB devices. See if it happens with that disconnected. Or possibly it's not shutting down at all so systemd / OS issue

**Comment by Zuluuk** [comment]
Confirmed that I have nothing connected and POWER_OFF_ON_HALT=1 also. 

The camera work is a bit shaky. 

https://www.veed.io/view/cc337f04-b6d6-489a-89d2-f7a543f5bacd?panel=showcase

**Comment by timg236** [comment]
It seems to be specific to your setup. Works on normal RPi OS mouse key board SSD.

We would need to see a uart log showing that it had entered shutdown.

It might be worth using a clean rpi  OS install and verifying that the power button boots the system when it is in this state.

Also are you using a Pi4 or Pi5 power supply ?

**Comment by Zuluuk** [comment]
> It seems to be specific to your setup. Works on normal RPi OS mouse key board SSD.
> 
> We would need to see a uart log showing that it had entered shutdown.
> 
> It might be worth using a clean rpi OS install and verifying that the power button boots the system when it is in this state.
> 
> Also are you using a Pi4 or Pi5 power supply ?

It can't be my setup, as there are nothing connected except for the usb c power, there is no OS there. I dont have a microsd in the bay or do i have a usb.

If it is not going into shutdown with a powerbutton press and standby on with no os then its a bug. No other computer system does that.

I was in the batocera chat and another user had similar issues. I never had this issue before, it only happen recently when i tried to use the GPIO to test the power feature to program a power button, I confirmed with the dev that he hasn't implemented the GPIO for pi5 yet, so i rolled back. This is when I noticed the issue, and tried to update eeprom etc.

Please see attached. https://github.com/batocera-linux/batocera.linux/issues/10844

To be honest, I think I have a fault hardware if you dont think its the eeprom, the weird and wonderful world of early adoption.

**Comment by timg236** [comment]
If the OS is not running then you have to hold the power button for at least 7 seconds to put the PMIC into standby. The short press is implemented by the OS in software.

By GPIO are you referring to the power button pads? It's not possible to use the 40-pin header for a power button on Pi5 because that's connected to RP1 and not the SOC.

There's a small chance that an issue with a USB-PD power supply could wakeup the board again, a plain USB-C power supply would rule that out.

My guess is that it has never entered STANDBY mode or was immediately woken up (hardware issue) because in STANDBY mode the PMIC disables 3.3V output (so fan will stop) and that's done in the PMIC IC itself.

**Comment by Zuluuk** [comment]
I have forced a shutdown by holding the power button for 7s+.

For the gpio I gathered as much as I couldn't get to work, and reported it to the dev already.

I have tested a generic usb a to c charging block and my cable. The same happens when forcing into standby with the power button.

**Comment by timg236** [comment]
Just to confirm the sequence


1. Disconnect power cable
2. DUT is powered on with no SD card and no peripherals and no RTC battery
3. Green LED is on
4. Press power button for 7 seconds
5. Green LED goes off
6. Red LED is on
7. Green LED immediately switches on  with USB and FAN active

If that is happening then either there is a hardware fault with the PMIC OR there is an issue with  USB-C power supply is resetting and causing DUT to power on.

**Comment by Zuluuk** [comment]
> Just to confirm the sequence
> 
>     1. Disconnect power cable
> 
>     2. DUT is powered on with no SD card and no peripherals and no RTC battery
> 
>     3. Green LED is on
> 
>     4. Press power button for 7 seconds
> 
>     5. Green LED goes off
> 
>     6. Red LED is on
> 
>     7. Green LED immediately switches on  with USB and FAN active
> 
> 
> If that is happening then either there is a hardware fault with the PMIC OR there is an issue with USB-C power supply is resetting and causing DUT to power on.

The steps you mentioned is exactly how I have reproduced the issue. I have tested now with 3 different power brick, 1 official psu. All give me the same issue. As I have chatted with another user, he didn't experience this issue either, so I would have to say its a hardware issue.

**Comment by pelwell** [comment]
I'm looking at the fan behaviour at the moment for other reasons using one of our active coolers, and with the latest bootloader EEPROM image (8th February 2024), `sudo poweroff` (or pushing the power button - twice if the GUI is running) causes the fan to stop, whether or not it was running at the time of shutdown. The POWER_OFF_ON_HALT only affects the USB power.

**Comment by Zuluuk** [comment]
> I'm looking at the fan behaviour at the moment for other reasons using one of our active coolers, and with the latest bootloader EEPROM image (8th February 2024), `sudo poweroff` (or pushing the power button - twice if the GUI is running) causes the fan to stop, whether or not it was running at the time of shutdown. The POWER_OFF_ON_HALT only affects the USB power.

I will try this later and reply directly. I don't think there's an issue with the fan controller. When I am in the os, the fan does not even start 😂. I also never had this issue before as I remember I shutdown and everything was pretty gucci, fan off, usb light off etc. This only happen recently when I tried the gpio and updated the eeprom to rule out any bugs. I am happy to test and help out as I do believe that contribution is why and how the raspberry pi have been so successful.

**Comment by timg236** [comment]
> > Just to confirm the sequence
> > ```
> > 1. Disconnect power cable
> > 
> > 2. DUT is powered on with no SD card and no peripherals and no RTC battery
> > 
> > 3. Green LED is on
> > 
> > 4. Press power button for 7 seconds
> > 
> > 5. Green LED goes off
> > 
> > 6. Red LED is on
> > 
> > 7. Green LED immediately switches on  with USB and FAN active
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If that is happening then either there is a hardware fault with the PMIC OR there is an issue with USB-C power supply is resetting and causing DUT to power on.
> 
> The steps you mentioned is exactly how I have reproduced the issue. I have tested now with 3 different power brick, 1 official psu. All give me the same issue. As I have chatted with another user, he didn't experience this issue either, so I would have to say its a hardware issue.

A couple of questions for hardware engineers.

- Please could we have a photo of the top side of the board showing the PMIC
- Does this still happen if the case fan is not connected - i.e. immediate wakeup

**Comment by Zuluuk** [comment]
> > > Just to confirm the sequence
> > > ```
> > > 1. Disconnect power cable
> > > 
> > > 2. DUT is powered on with no SD card and no peripherals and no RTC battery
> > > 
> > > 3. Green LED is on
> > > 
> > > 4. Press power button for 7 seconds
> > > 
> > > 5. Green LED goes off
> > > 
> > > 6. Red LED is on
> > > 
> > > 7. Green LED immediately switches on  with USB and FAN active
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If that is happening then either there is a hardware fault with the PMIC OR there is an issue with USB-C power supply is resetting and causing DUT to power on.
> > 
> > 
> > The steps you mentioned is exactly how I have reproduced the issue. I have tested now with 3 different power brick, 1 official psu. All give me the same issue. As I have chatted with another user, he didn't experience this issue either, so I would have to say its a hardware issue.
> 
> A couple of questions for hardware engineers.
> 
>     * Please could we have a photo of the top side of the board showing the PMIC
> 
>     * Does this still happen if the case fan is not connected - i.e. immediate wakeup

Hi timg236,
https://www.veed.io/view/d4280b33-0f48-4f17-8a25-0dd71906ad44?panel=share this is the check from red to green. It's not instant, it's approximately 1s.

Photo of the board attached. As I don't have macro mode. I took a few just in case some details are missing. 
![IMG_20240209_153649](https://github.com/raspberrypi/rpi-eeprom/assets/159487901/4031e5c2-05ff-48f3-b8ae-847b5f66111c)
![IMG_20240209_153639](https://github.com/raspberrypi/rpi-eeprom/assets/159487901/4331774d-cdf1-490e-9d0d-9978d4d9db9b)
![IMG_20240209_153604](https://github.com/raspberrypi/rpi-eeprom/assets/159487901/23d02f9d-2034-401c-9847-f6f168165e54)
![IMG_20240209_153600](https://github.com/raspberrypi/rpi-eeprom/assets/159487901/a8be909b-0ec4-4fe8-b702-9d48beac7f3a)

**Comment by Zuluuk** [comment]
> I'm looking at the fan behaviour at the moment for other reasons using one of our active coolers, and with the latest bootloader EEPROM image (8th February 2024), `sudo poweroff` (or pushing the power button - twice if the GUI is running) causes the fan to stop, whether or not it was running at the time of shutdown. The POWER_OFF_ON_HALT only affects the USB power.

Hi pelwell,
When I am in the os the fan stopped. As soon as I entered that command the light turn red and the fan goes full speed.

**Comment by pelwell** [comment]
I understand - I was just confirming that something is not right with your system.

**Comment by timg236** [comment]
I checked the code and USB + RP1 are not initialised until after DDR init so not quite instant. Something is resetting the PMIC and causing it to leave standby, probably hardware related but I can't think what.

**Comment by Zuluuk** [comment]
> Out of interest, what does it say on the chip on the bottom left of the board by the USB-C port (the PMIC). Probably not significant though!

Not sure if you able to see this
![Uploading IMG_20240209_201926.jpg…]()

**Comment by timg236** [comment]
Thanks. It’s the part that we would expect so that’s not the issue. This failure mode has got me stumped. 
I’ll follow on Monday about whether we could get the board back (and send you replacement etc) if you at happy to do that and logistics are feasible.

**Comment by Zuluuk** [comment]
> Thanks. It’s the part that we would expect so that’s not the issue. This failure mode has got me stumped. I’ll follow on Monday about whether we could get the board back (and send you replacement etc) if you at happy to do that and logistics are feasible.

Happy to help, I live in Dublin(Ireland), do let me know. At this time i am also waiting for pihut to reply to my rma request, which is taking a while to even have someone engaged.

**Comment by timg236** [comment]
@Zuluuk Please can you contact info@raspberrypi.com mentioning this issue with your name, email and phone number for shipping - add "Tim Gover"

For this Pi5 please don't use the RMA process, we want to get the board directly and as soon as we receive it we can send you a replacement board plus something to compensate for postage.

If you contact info@raspberrypi.com with your name, address, email and phone number mentioning this bug we can sort it out via email.

**Comment by Zuluuk** [comment]
> "Tim Gover"

Thanks Tim, I have sent the email to info. At the weekend, I have checked with the developer for Batocera. He has confirmed that there are customisation / flashing of the eeprom from any of his image. During my conversation another user also reported a similar issue to mine. Hope you can rootcause it.

I will update pihut now to cancel my RMA.

Have a good day.

**Comment by timg236** [comment]
The board arrived. Thanks!

The issue was related to a hardware fault related to the USB current limiter / VBUS switch. This is why the FAN was on when the PMIC is in standby since USB VBUS is not a PMIC output, it's from 5V but goes via a switch.

Closing this as a software bug and the board is with hardware team. 

Please let us know if there's any issue with the replacement since you have my email.

**Comment by Lewiscowles1986** [comment]
I'd like to understand this so that I can make mine spin all the time. I Altered /boot/firmware/config.txt to lower the thresholds all to 1000, and set the fan speed value to 255. When it's powering on or off, I get fan. When it is not, I've not seen the fan doing anything, and I think it's because someone over at RaspberryPi "was helping" (and should be prevented from helping anyone else).

I want the fan. Even when it is not needed, all the time!

**Comment by pelwell** [comment]
> someone over at RaspberryPi "was helping" (and should be prevented from helping anyone else)

Wow.

**Comment by lurch** [comment]
> I want the fan. Even when it is not needed, all the time!

https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#fan-connector-pinout shows the fan-pinout, so I guess if you want it running all the time the easiest way of achieving that would be to connect the 5V and GND wires of the fan directly to the 5V and GND pins on the Pi's main GPIO header? Although I've not tried this myself, so I dunno if the fan would actually work when wired like that.

**Comment by pelwell** [comment]
> I guess if you want it running all the time the easiest way of achieving that would be to connect the 5V and GND wires of the fan directly to the 5V and GND pins on the Pi's main GPIO header?

Nope - even when the fan is stopped, the 5V signal will be on - changing it to a different 5V source won't make any difference. The fan has a speed control signal that is normally driven by a PWM. Driving it low will cause the fan to constantly spin at maximum speed:
```
pi@raspberrypi:~$ sudo pinctrl | grep FAN
29: no    pu | hi // FAN_TACH/GPIO29 = none
45: a0    pd | hi // FAN_PWM/GPIO45 = PWM1_CHAN3
pi@raspberrypi:~$ sudo pinctrl FAN_PWM op dl
```
Note that this will need to be done after each reboot. If you want to restore the kernel driver's control of the fan speed:
```
pi@raspberrypi:~$ sudo pinctrl FAN_PWM a0
```

**Comment by Lewiscowles1986** [comment]
> sudo pinctrl FAN_PWM op dl

This was the trick. Apologies I missed all the replies. I got it from stackoverflow same day I posted this and forgot to come back here.

I use systemd to start it on boot. I was hoping that there would be a systemd service, or other alteration I can run to prevent the attempt at being helpful (which I still don't appreciate)

**Comment by joeuhren** [comment]
> The board arrived. Thanks!
> 
> The issue was related to a hardware fault related to the USB current limiter / VBUS switch. This is why the FAN was on when the PMIC is in standby since USB VBUS is not a PMIC output, it's from 5V but goes via a switch.
> 
> Closing this as a software bug and the board is with hardware team.
> 
> Please let us know if there's any issue with the replacement since you have my email.

@timg236 Curious that this is mentioned as a software bug. Are there steps I can take to stop this from happening to my rpi5? It was working great for months and now out of the blue the fan spins at full blast and doesn't stop when I shut down. Everything else seems to work fine. Running newest eeprom from Sep-23 tried POWER_OFF_ON_HALT=1 all the same troubleshooting as above but can't seem to stop this behavior.

**Comment by ToKe79** [comment]
First off all sorry for reviving this closed issue.

@joeuhren: As the issue of the OP is **not** a software/firmware bug, the issue was closed and handed over to the HW dev team. So there is nothing in SW/FW (I suppose) to fix this behavior.

@timg236: If I may ask, what is the recommended route to handle these issues for other users? Should they RMA the board where it was purchased, or should they contact Raspberry directly? I have a friend in the US with what looks same issue - after running `shutdown` or `poweroff` the OS turns off, green led switches to red and the fan starts spinning at 100 %. Thank you in advance for any response, even a negative one.

**Comment by forkymcforkface** [comment]
Ive been having this same issue, any fixes other than RMA? Sadly I bought this right when it came out and is now out of warranty. Id love for my pi5 to be able to shutdown without the fans going full blast.

**Comment by elcatedratico** [comment]
I have the same problem as mentioned before. 
As soon as I power off the system, the fan starts spinning full power. There is no other hardware than the original power supply connected. 
Don't know what to do now.

**Comment by psp631** [comment]
Is your problem solved? I'm having the exact same issue.

**Comment by elcatedratico** [comment]
In fact, the problem has been solved. I sent the Pi back to the manufacturer and there the problem was checked. As already written by many users, it is a hardware defect.

I was able to complain about the Pi and got a new one. This works flawlessly.

**Comment by forkymcforkface** [comment]
I was able to solve this by doing a full eeprom and firmware update
