### ISSUE TITLE
Allow updating with older EEPROM .sig timestamp

### ISSUE THREAD

**Issue by Jbontt** [raspberrypi/rpi-eeprom#542]
### Describe the bug

Newer versions of the bootloader check the `update-ts` of the bootloader and compare it with the `ts: <unix-ts>` in the `.sig` file.
This means that updating the EEPROM with an older timestamp is not possible.
Can an option be added to the config.txt to override this behavior?

### Steps to reproduce the behaviour

* Generate an EEPROM .upd and .sig file
* Place those on USB stick 1
* Generate a newer EEPROM .upd and .sig file
* Place those on USB stick 2
* Flash the EEPROM with USB stick 2
* Try to flash the EEPROM with USB stick 1
* This will be skipped due to an older timestamp

### Device (s)

Raspberry Pi 4 Mod. B

### Bootloader configuration.

ENABLE_SELF_UPDATE=1

**Comment by timg236** [comment]
The purpose of the timestamp is to not install old / out of date updates and avoid cycling dependencies.
If that behaviour is not desired then the timestamp can be removed from the .sig file.

**Comment by timg236** [comment]
You could create a newer timestamp or use pieeprom.bin / pieeprom.sig to a recovery update.

Adding a force old timestamp would be unnecessary complexity. The other option is to use flashrom

**Comment by Jbontt** [comment]
@timg236 I will try to use the `pieeprom.bin / pieeprom.sig` path.
Based on the documentation, am I correct to assume that I can only use `pieeprom.bin / pieeprom.sig` when booting from a SD card and thus not from a USB stick?

**Comment by timg236** [comment]
Yes, that's what the RPi Imager bootloader recovery images do.

So you can insert the MSD / SD in a bunch of devices

**Comment by Jbontt** [comment]
@timg236 thanks for your suggestion

**Comment by timg236** [comment]
One improvement. Add 'rpi-eeprom-digest' do the USB stick. When you want to update your Pi's with the image on the USB drive mount it in a suitable Linux / Cygwin environment and run the following to regenerate the signature

rpi-eeprom-digest -i pieeprom.upd -o pieeprom.sig
