### ISSUE TITLE
TFTP boot is not using full serial number

### ISSUE THREAD

**Issue by mast** [raspberrypi/rpi-eeprom#563]
### Describe the bug

Documentation saying that when TFTP_PREFIX=0 is set (default), serial number should be used as a prefix during TFTP file retrieval.
Although it seems bootloader only sends least significant 4 bytes of serial number.

On RPI4's most significant 4 bytes of serial number was always 10000000, which is not the case for RPI5.
I have several RPI5 boards and they all have different most significant bytes of serial number.
That makes me worry about uniqueness of least significant bytes in case of RPI5. If they are not unique it might cause issues when net booting such boards, as tftp prefix suppose uniquely identify kernel to boot.

![tftp-prefix](https://github.com/raspberrypi/rpi-eeprom/assets/277947/3363fff5-5785-4748-94fa-31e684c0d20b)

```
cat /sys/firmware/devicetree/base/serial-number 
0c8f7e5cbd989ae1
```

### Steps to reproduce the behaviour

- configure board to netboot
- and see bootp/tftp tcp dump

### Device (s)

Raspberry Pi 5

### Bootloader configuration.

[all]
BOOT_UART=1
POWER_OFF_ON_HALT=0
BOOT_ORDER=0xf261

```
BOOTLOADER: up to date
   CURRENT: Fri Feb 16 15:28:41 UTC 2024 (1708097321)
    LATEST: Fri Feb 16 15:28:41 UTC 2024 (1708097321)
   RELEASE: default (/lib/firmware/raspberrypi/bootloader-2712/default)
            Use raspi-config to change the release.
```

### Network (TFTP boot)

dnsmasq.conf:

interface=eth0
port=0
dhcp-range=10.14.0.255,proxy
log-dhcp
enable-tftp
tftp-root=/home/admin/research/netboot/tftp
pxe-service=0,"Raspberry Pi Boot"

**Comment by pelwell** [comment]
Don't you think that changing this would cause more problems than it fixes?

**Comment by peterharperuk** [comment]
They're set to a random random number in the factory.

**Comment by mast** [comment]
alright, so it's 1 out of 2^32, it doesn't sound bad. I will let you decide then what to do with this ticket.
btw, is there any way to redefine parent path bootloader will use via some DHCP option inside offer (67 or some vendor specific?)?
or the only way is to deal with some file system magic on tftp end?
