### ISSUE TITLE
Latest Eeprom for raspberry pi 4 

### ISSUE THREAD

**Issue by actraiser30** [raspberrypi/rpi-eeprom#633]
### Describe the bug

Hello I'm searching to install the latest eeprom for raspberry pi 4 2024-10-21 as mentioned in the releases page,but I cannot find it,rpi-imager gives as latest the 2023-01-18. That I already have installed.

### Steps to reproduce the behaviour

.

### Device (s)

Raspberry Pi 4 Mod. B

### Bootloader configuration.

.

### System

.

**Comment by peterharperuk** [comment]
Try...

sudo apt update
sudo apt install rpi-eeprom
sudo rpi-eeprom-update -a

**Comment by timg236** [comment]
Thanks @peterharperuk 

N.B. Releases older than the last automatic update will be deleted from rpi-eeprom APT packages. The old releases are archived in the 'old' directories here

https://github.com/raspberrypi/rpi-eeprom/tree/master/firmware-2711/old
