### ISSUE TITLE
BOOT_UART default 1 breaks hats using gpio 14 and 15

### ISSUE THREAD

**Issue by digitalLumberjack** [raspberrypi/rpi-eeprom#643]
### Describe the bug

Hello :)

With the commit https://github.com/raspberrypi/rpi-eeprom/commit/d57c084c9fd2cb7fc08f4b1ab2387df695067371

The bootloader enable by default BOOT_UART=1 and break support for hats using gpio 14 and 15

### Steps to reproduce the behaviour

Update bootloader, reboot with a hat using gpio 14 and 15, see the error.

When setting BOOT_UART=0, ~it works again~

EDIT seems like it does not work again with BOOT_UART=0

### Device (s)

Raspberry Pi 5

### Bootloader configuration.

[all]
BOOT_UART=1
POWER_OFF_ON_HALT=0
BOOT_ORDER=0xf41

### System
```
[    6.226339] pinctrl-rp1 1f000d0000.gpio: pin gpio14 already requested by 1f00030000.serial; cannot claim for 1f00148000.dpi
```

**Comment by pelwell** [comment]
We are aware, and a fix is in progress. In the meantime, `enable_uart=0` in config.txt should work around the problem.

**Comment by lurch** [comment]
> With the commit [d57c084](https://github.com/raspberrypi/rpi-eeprom/commit/d57c084c9fd2cb7fc08f4b1ab2387df695067371)
> 
> The bootloader enable by default BOOT_UART=1 and break support for hats using gpio 14 and 15

FYI I suspect it was actually https://github.com/raspberrypi/rpi-eeprom/commit/fe7bfc720165464d9dfe2f85fe090ca22a625bd7 that changed the behaviour here. (This is just for information; I'm sure that Phil's fix will cure this issue)

**Comment by digitalLumberjack** [comment]
Thank you, sorry if the feedback was a little bit to early.

**Comment by lurch** [comment]
No need to apologise, there's no way for you to know that we were already aware of the issue! Thank you for your report.
We spotted this issue ourselves only a couple of days ago :slightly_smiling_face:

**Comment by timg236** [comment]
I think the apt update will be wk2 now

**Comment by timg236** [comment]
@nbuchwitz We managed to get the update out today - last one of the year I hope :)

**Comment by nbuchwitz** [comment]
Thanks. I guess this can be closed then?
