### ISSUE TITLE
Raspberry PI-4B. rpi-eeprom adds garbage to IP address of TFTP server 

### ISSUE THREAD

**Issue by VladVons** [raspberrypi/rpi-eeprom#72]
Raspberry PI 4B
pieeprom-2019-12-03.bin 

firmware has a problem while network booting to TFTP server.
If TFTP server's IP lass than 3 digits  pieeprom pads to IP value 3 digits with a garbage.

/etc/dhcp/dhcpd.conf
option tftp-server-name "192.168.0.21";

tcpdump gets following string
00:12:47.464387 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.2.214 tell ...

our 192.168.0.21 becomes 192.168.2.214 and nothing comes to our real TFTP server, while we awaitig for requests on 192.168.0.21

in case we set 3 digit it works good
option tftp-server-name "192.168.0.211";

**Comment by timg236** [comment]
Might be a regression in the parsing code in that release. If you can specify the extension directly then appending a space might fix it. Should be trivial to fix, will take a look in the New Year

**Comment by timg236** [comment]
This should be fixed in the 2020-01-09 release. 
Please could you give this a try ?
https://github.com/timg236/rpi-eeprom/tree/rpiboot-2020-01-19/firmware/beta

**Comment by timg236** [comment]
I believe this is fixed. Closing bug - please re-open if this is not the case.
