### ISSUE TITLE
Cannot install specific bootloader and vl805 files in the same session

### ISSUE THREAD

**Issue by m-roberts** [raspberrypi/rpi-eeprom#80]
```
sudo rpi-eeprom-update -f /lib/firmware/raspberrypi/bootloader/critical/pieeprom-2019-07-15.bin
sudo rpi-eeprom-update -u /lib/firmware/raspberrypi/bootloader/critical/vl805-00013701.bin
```

Ideally, these commands should place the following files in BOOTFS:
```
pieeprom.sig
pieeprom.upd
vl805.bin
vl805.sig
```

However, `removePreviousUpdates` will remove the first 2 when installing the second 2, and vice versa. There is no option to avoid this step.

Similarly, `rpi-eeprom-update -A bootloader` and `rpi-eeprom-update -A vl805` do the same thing.

**Comment by timg236** [comment]
You just need to run this as once command assuming you have the latests version of the script

**Comment by m-roberts** [comment]
cool!
