### ISSUE TITLE
AARCH64 ARMV8 support?

### ISSUE THREAD

**Issue by br6** [raspberrypi/rpi-eeprom#81]
will support for 64bit be impletement, 
debian64 archlinux64 and gentoopi64 is available.
vl805 and userland is working in 64bit

**Comment by timg236** [comment]
The supported method for vl805 updates is via recovery.bin which runs on the VPU and is therefore independent of the host-OS. The vl805 executable is deprecated and will probably be removed from this package once the bootloader EEPROM is able to program VL805 itself i.e. without recovery.bin

**Comment by timg236** [comment]
Dependency on vl805 removed. A 64bit version of this package will be available soon
