### ISSUE TITLE
Starting from EMMC (pi4)

### ISSUE THREAD

**Issue by custodis-intestina** [raspberrypi/rpi-eeprom#89]
Hi there
From boot loader 11/18/19
I'm testing the start of EMMC cards (ODroid with adapter)
Raspbian starts without problems.
PINN and NOOBS do not start.
Ubuntu 32Bit and 64bit do not start either.

It is important for me that EMMC starts. (3 SD cards already destroyed)
I test a lot

Sry for Google Translation ;-)

**Comment by timg236** [comment]
If Raspbian is starting then it's not a bootloader issue. Most likely PINN / NOOBs / Ubuntu have old videocore firmware so it would be best to ask on those forums
